const testGrid1 = [
    [{ status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "selectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }],
     [{ status: "selectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "selectable", content: "empty", groundHealth: 3 }],
     [{ status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }],
     [{ status: "selectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "selectable", content: "empty", groundHealth: 3 }],
     [{ status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "selectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }]
]

const testGrid2 = [
    [{ status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }],
     [{ status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }],
     [{ status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }],
     [{ status: "selectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "selectable", content: "empty", groundHealth: 3 }],
     [{ status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 },
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }, 
     { status: "unselectable", content: "empty", groundHealth: 3 }]
]

export default testGrid2;